spring:
  application:
    name: DonorTrack
  datasource:
    url: jdbc:postgresql://localhost:5432/donortrack
    username: postgres
    password: 010909
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    username: donor.track.official@gmail.com
    password: fcmcdgslqblnudlq
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

info:
  app:
    name: ${spring.application.name}
    version: 0.0.1
    description: DonorSearch fork

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security.web.access: DEBUG
    org.springframework.security.web.util.matcher: DEBUG